export const APPOINTMENT_CONSTANTS = {
  SLOT_GRANULARITY_MINUTES: 15,
} as const;

export const APPOINTMENT_ERROR_CODES = {
  ONLINE_BOOKING_DISABLED: 'ONLINE_BOOKING_DISABLED',
  APPOINTMENT_SLOT_UNAVAILABLE: 'APPOINTMENT_SLOT_UNAVAILABLE',
  APPOINTMENT_SESSION_NOT_BOOKABLE: 'APPOINTMENT_SESSION_NOT_BOOKABLE',
  APPOINTMENT_TYPE_SESSION_MISMATCH: 'APPOINTMENT_TYPE_SESSION_MISMATCH',
  ACTIVE_CONSULTATION_EXISTS: 'ACTIVE_CONSULTATION_EXISTS',
  PATIENT_ARCHIVED_CANNOT_BOOK: 'PATIENT_ARCHIVED_CANNOT_BOOK',
  APPOINTMENT_PAST_NOT_ALLOWED: 'APPOINTMENT_PAST_NOT_ALLOWED',
  APPOINTMENT_OUTSIDE_HORIZON: 'APPOINTMENT_OUTSIDE_HORIZON',
  TREATMENT_SESSION_REQUIRED: 'TREATMENT_SESSION_REQUIRED',
  APPOINTMENT_OUTSIDE_CANCEL_RESCHEDULE_WINDOW:
    'APPOINTMENT_OUTSIDE_CANCEL_RESCHEDULE_WINDOW',
  APPOINTMENT_NOT_RESCHEDULABLE: 'APPOINTMENT_NOT_RESCHEDULABLE',
  APPOINTMENT_NOT_CANCELLABLE: 'APPOINTMENT_NOT_CANCELLABLE',
  APPOINTMENT_NOT_CONFIRMABLE: 'APPOINTMENT_NOT_CONFIRMABLE',
  APPOINTMENT_NOT_REJECTABLE: 'APPOINTMENT_NOT_REJECTABLE',
  APPOINTMENT_NOT_CHECKABLE: 'APPOINTMENT_NOT_CHECKABLE',
  APPOINTMENT_CHECKIN_CODE_INVALID: 'APPOINTMENT_CHECKIN_CODE_INVALID',
  APPOINTMENT_CHECKIN_OUTSIDE_GEOFENCE: 'APPOINTMENT_CHECKIN_OUTSIDE_GEOFENCE',
  CLINIC_LOCATION_NOT_CONFIGURED: 'CLINIC_LOCATION_NOT_CONFIGURED',
  APPOINTMENT_CHECKIN_NONE_TODAY: 'APPOINTMENT_CHECKIN_NONE_TODAY',
  APPOINTMENT_CHECKIN_AMBIGUOUS: 'APPOINTMENT_CHECKIN_AMBIGUOUS',
} as const;
