/**
 * Authentication and authorization constants.
 */
export const AUTH_CONSTANTS = {
  PUBLIC_ROUTE: 'isPublic',
  REQUIRED_PERMISSIONS: 'requiredPermissions',
  AUDIT_ACTION: 'auditAction',
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_TOKEN: 'INVALID_TOKEN',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  CANNOT_DISABLE_LAST_ADMIN: 'CANNOT_DISABLE_LAST_ADMIN',
  CANNOT_DISABLE_SELF: 'CANNOT_DISABLE_SELF',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  ACCOUNT_NOT_INVITED: 'ACCOUNT_NOT_INVITED',
  PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
} as const;

export const JWT_DEFAULTS = {
  ACCESS_EXPIRES_IN: '15m',
  REFRESH_EXPIRES_IN: '7d',
} as const;