/**
 * Authentication and authorization constants.
 */
export const AUTH_CONSTANTS = {
  PUBLIC_ROUTE: 'isPublic',
  REQUIRED_PERMISSIONS: 'requiredPermissions',
  AUDIT_ACTION: 'auditAction',
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  CANNOT_DISABLE_LAST_ADMIN: 'CANNOT_DISABLE_LAST_ADMIN',
  CANNOT_DISABLE_SELF: 'CANNOT_DISABLE_SELF',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  ACCOUNT_NOT_INVITED: 'ACCOUNT_NOT_INVITED',
  NEW_PHONE_SAME_AS_CURRENT: 'NEW_PHONE_SAME_AS_CURRENT',
  PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',
  ACCOUNT_PENDING_ACTIVATION: 'ACCOUNT_PENDING_ACTIVATION',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  ACCOUNT_ALREADY_INVITED: 'ACCOUNT_ALREADY_INVITED',
} as const;

export const JWT_DEFAULTS = {
  ACCESS_EXPIRES_IN: '15m',
  REFRESH_EXPIRES_IN: '7d',
} as const;