export const CHATBOT_CONSTANTS = {
  TRIAGE_MAX_TURNS: 6,
  EDUCATION_MAX_TURNS: 12,
  DEFAULT_MODEL: 'gemini-2.5-flash',
} as const;

export enum ChatbotMode {
  TRIAGE = 'TRIAGE',
  EDUCATION = 'EDUCATION',
}

export const CHATBOT_ERROR_CODES = {
  CHATBOT_UNAVAILABLE: 'CHATBOT_UNAVAILABLE',
  CHATBOT_TURN_LIMIT: 'CHATBOT_TURN_LIMIT',
  CHATBOT_SUMMARIZE_INVALID: 'CHATBOT_SUMMARIZE_INVALID',
} as const;
