export const FINANCIAL_ERROR_CODES = {
  INVALID_INVOICE_ITEMS: 'INVALID_INVOICE_ITEMS',
  INVALID_INVOICE_ITEM_QUANTITY: 'INVALID_INVOICE_ITEM_QUANTITY',
  INVALID_INVOICE_ITEM_UNIT_PRICE: 'INVALID_INVOICE_ITEM_UNIT_PRICE',
  INVALID_INVOICE_RELATION: 'INVALID_INVOICE_RELATION',
  PATIENT_ARCHIVED_CANNOT_INVOICE: 'PATIENT_ARCHIVED_CANNOT_INVOICE',
  INVALID_PAYMENT_AMOUNT: 'INVALID_PAYMENT_AMOUNT',
  PAYMENT_EXCEEDS_REMAINING: 'PAYMENT_EXCEEDS_REMAINING',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_VOID: 'INVOICE_VOID',
} as const;
