export const NOTIFICATION_TYPES = {
  SYSTEM: 'SYSTEM',
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_PENDING_CONFIRMATION: 'APPOINTMENT_PENDING_CONFIRMATION',
  APPOINTMENT_REMINDER: 'APPOINTMENT_REMINDER',
  INVOICE_CREATED: 'INVOICE_CREATED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  TREATMENT_SESSION_BOOKABLE: 'TREATMENT_SESSION_BOOKABLE',
  APPOINTMENT_PENDING_STAFF: 'APPOINTMENT_PENDING_STAFF',
  APPOINTMENT_CANCELLED_BY_PATIENT: 'APPOINTMENT_CANCELLED_BY_PATIENT',
  APPOINTMENT_RESCHEDULED_BY_PATIENT: 'APPOINTMENT_RESCHEDULED_BY_PATIENT',
  APPOINTMENT_CHECKED_IN: 'APPOINTMENT_CHECKED_IN',
  APPOINTMENT_WAITING: 'APPOINTMENT_WAITING',
} as const;

export const STAFF_NOTIFICATION_ROLE_CODES = ['DOCTOR', 'SECRETARY'] as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export const NOTIFICATION_SOCKET_NAMESPACE = '/notifications';
export const NOTIFICATION_SOCKET_EVENT = 'notification.created';

export function accountNotificationRoom(accountId: number): string {
  return `account:${accountId}`;
}

export const NOTIFICATION_ERROR_CODES = {
  INVALID_DEVICE_TOKEN: 'INVALID_DEVICE_TOKEN',
  DEVICE_TOKEN_FORBIDDEN: 'DEVICE_TOKEN_FORBIDDEN',
} as const;

export const FCM_PERMANENT_ERROR_CODES = new Set([
  'messaging/registration-token-not-registered',
  'messaging/invalid-registration-token',
]);
