export const TREATMENT_CONSTANTS = {
  TEETH_COUNT: 48,
  CONSULTATION_TITLE_AR: 'زيارة أولى (استشارة)',
  CONSULTATION_TITLE_EN: 'First Visit (Consultation)',
} as const;

export const TREATMENT_ERROR_CODES = {
  SESSION_ORDER_ALREADY_EXISTS: 'SESSION_ORDER_ALREADY_EXISTS',
  TEMPLATE_HAS_NO_SESSIONS: 'TEMPLATE_HAS_NO_SESSIONS',
  PLAN_NAME_REQUIRED: 'PLAN_NAME_REQUIRED',
  SESSION_NOT_STARTABLE: 'SESSION_NOT_STARTABLE',
  SESSION_NOT_COMPLETABLE: 'SESSION_NOT_COMPLETABLE',
  SESSION_NOT_CANCELLABLE: 'SESSION_NOT_CANCELLABLE',
  SESSION_NOT_UPDATABLE: 'SESSION_NOT_UPDATABLE',
  RATING_WINDOW_EXPIRED: 'RATING_WINDOW_EXPIRED',
  RATING_ALREADY_SUBMITTED: 'RATING_ALREADY_SUBMITTED',
  SESSION_NOT_RATEABLE: 'SESSION_NOT_RATEABLE',
  INVALID_TEETH_LENGTH: 'INVALID_TEETH_LENGTH',
  APPOINTMENT_PATIENT_MISMATCH: 'APPOINTMENT_PATIENT_MISMATCH',
  PLAN_STATUS_MUST_BE_CANCELLED: 'PLAN_STATUS_MUST_BE_CANCELLED',
  INVALID_ATTACHMENT_FILE_COUNT: 'INVALID_ATTACHMENT_FILE_COUNT',
} as const;
